const fs = require("fs");
const path = require("path");

const basePath = "c:/Users/USER/Desktop/AiXpertLabs/DealSense/apps/web-dashboard/src/pages";

const premiumWhiteStyle = `style={{
          background: "#ffffff",
          padding: "20px 24px",
          border: "1px solid var(--hs-border-dark)",
          borderTop: "3px solid var(--hs-primary)",
          marginBottom: "var(--sp-5)",
          boxShadow: "var(--shadow-sm)",
        }}`;

const files = fs.readdirSync(basePath).filter(f => f.endsWith(".tsx"));

for (const f of files) {
  const filePath = path.join(basePath, f);
  let content = fs.readFileSync(filePath, "utf-8");
  let modified = false;

  // Replace dark gradient style block with white premium style
  const darkGradientRegex = /style=\{\{\s*background:\s*"linear-gradient\(135deg,\s*#124548[^}]*\}\}/g;
  
  if (darkGradientRegex.test(content)) {
    content = content.replace(darkGradientRegex, premiumWhiteStyle);
    modified = true;
  }

  // Also fix text colors in the header to match the white background
  
  if (modified) {
    // We only want to replace these specific colors if they are inside the header. 
    // To be safe, we'll replace the exact lines that were generated by our previous script.
    content = content.replace(/color: "#ffffff", margin: "0 0 4px"/g, 'color: "var(--hs-heading)", margin: "0 0 4px"');
    content = content.replace(/color: "#ffffff", margin: "4px 0 6px"/g, 'color: "var(--hs-heading)", margin: "4px 0 6px"'); // for waterfall/playbooks

    content = content.replace(/color: "#d9e8e8"/g, 'color: "var(--hs-text)"');
    content = content.replace(/color: "#a5c2c4"/g, 'color: "var(--hs-text-muted)"');
    content = content.replace(/background: "rgba\(0, 164, 189, 0\.25\)", color: "#7de2ea"/g, 'background: "rgba(0, 164, 189, 0.1)", color: "#00a4bd"');
    content = content.replace(/background: "rgba\(255, 92, 53, 0\.25\)", color: "#ff7a59"/g, 'background: "rgba(255, 92, 53, 0.1)", color: "#ff5c35"'); // DealWarRoom badge
    
    fs.writeFileSync(filePath, content, "utf-8");
    console.log("Updated", f);
  }
}
